### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sobytes** [apra-informatica/Ti.ImageGallery#2]
Do you have a example app with this working?

**Comment by nonno** [comment]
No, sorry. But I used it in two different projects so I think it's 
enough flexible.
What you need is a collection of local images and a View as container 
for the widget (obviously you should get the view from the widget, 
widget.getView()), and following the example.

Il 02/09/15 00:12, SoBytes ha scritto:

**Comment by sobytes** [comment]
Hi Nonno,

Thanks for replaying just having issues understandind how you apply the images array?

```
var itemImages = [{
    'filepath' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg', // image detail path
    'filename' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg', // image detail filename
    'filepathThumb' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg',
}];

var imagesData = itemImages.map(function(itemImage) {
    return {
        'filepath' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg', // image detail path
        'filename' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg', // image detail filename
        'filepathThumb' : 'http://www.hdwallpapersimages.com/wp-content/uploads/2014/01/Winter-Tiger-Wild-Cat-Images.jpg', // image thumb path
        'fetchFunction' : function(params) {// function for fetching of detail image
            params = params || {};
            params.success = params.success ||
            function() {
                return;
            };
            params.error = params.error ||
            function(e) {
                Ti.API.warn(e);
            };

            // ...
        },
        'fetchFunctionThumb' : function(params) {// function for fetching of thumb image
            params = params || {};
            params.success = params.success ||
            function() {
                return;
            };
            params.error = params.error ||
            function(e) {
                Ti.API.warn(e);
            };
            // ...
        }
    };
});

gallery = Alloy.createWidget('it.apra.tiimagegallery', {
    'imagesData' : imagesData,
    'backgroundColor' : 'white',
    'emptyViewLabelParams' : {
        'color' : 'black'
    },
    'thumbsDefaultImage' : '/images/imageUnavailable.png'
});
```

And my view is.

```
<Alloy>
    <Window class="container">
        <Require type="widget" src="it.apra.tiimagegallery" id="gallery"></Require>
    </Window>
</Alloy>
```

Any suggestion would be great going to work my way through the modules on gittio and build sample project from as many of them as i can.

Thanks

Sam

**Comment by nonno** [comment]
Widget's code is quite easy to read, by the way:
"itemImages" is an array of object literals, containing all the info you 
need (filename, extensions, directories, ...).
"map" is the array.map standard function 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

You should compose 'filepath' with the complete path to your full-size 
image (using itemImage properties, made as you wish), 'filename' is the 
filename of the full-size image...
You can use 'fetchFunction' and 'fetchFunctionThumb' for defining the 
functions the widget will use in case it cannot find the files in the 
paths you gave it.

For example my files follow a convention, and their names are composed 
with an id and an extension:

var imagesData = currentFileEntries.map(function(currentFileEntry){
     var filepath = baseDir.nativePath + "/detail/" + 
currentFileEntry.id + '.' + currentFileEntry.extension;
     var filepathThumb = baseDir.nativePath + "/" + currentFileEntry.id 
- '.' + currentFileEntry.extension;
  
   return {
       'filepath' : filepath,
       'filename' : currentFileEntry.filename,
       'filepathThumb' : filepathThumb,
       'fetchFunction' : function(params){
           params = params || {};
           params.success = params.success || function(){return;};
           params.error = params.error || function(e) { Ti.API.warn(e); };
  
  ```
       galleryService.getImage({
           'folderId' : currentFileEntry.parentId,
           'filename' : currentFileEntry.filename,
           'dest' : filepath,
           'uuid' : currentFileEntry.id,
           'success' : params.success,
           'error' : params.error
       });
   },
  ```
  
  ....

Il 02/09/15 10:13, SoBytes ha scritto:

**Comment by fahad86** [comment]
Hi @nonno does this module/widget work with remote images as well??

**Comment by nonno** [comment]
Not directly, it downloads images locally and after it shows them.
